### ISSUE TITLE
S-Miles Cloud stopped pulling data

### ISSUE THREAD

**Issue by esommerfeld** [suaveolent/ha-hoymiles-wifi#12]
the integration in HA works great, but since then the s-miles cloud no longer retrieves any data. is it somehow possible to use both? thank you!

**Comment by suaveolent** [comment]
Thanks for the report. You are right. Might be due to too many requets. I will try to increase the time of certain functionality (e.g. sw. version) and see if it fixes the problem.

**Comment by esommerfeld** [comment]
Weird: In reality, S-Miles retrieves the data every 15 minutes, but doesn't update the time. :D

**Comment by suaveolent** [comment]
Already found the bug. I need to increase the interval to retrieve the Diagnostics data of the DTU (e.g. HW / SW ) version. Then update of app is working again. Will fix with next release (or update to main)
