### ISSUE TITLE
Guide how to use the data for the energy page in HA

### ISSUE THREAD

**Issue by ThomWee** [suaveolent/ha-hoymiles-wifi#15]
Thanks for this extension.

**Describe the bug**
I'm trying to configure the energy tab in my HA making use of the current Wh produced by my panels. But somehow the data displayed are never matching the output. I'm new to this topic, so maybe I'm understanding something wrong.

**To Reproduce**
My HA instance is running as a docker image on my raspberry pi. HA is running as version 2024.1.5 and your extension in version 0.1.4. Language I'm using is German.

I did configure the energy page to display Port 1/2 DC power.
![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/4629834/08a4cbff-fa36-484b-88d6-99bc56fd8446)

But the final results are just wrong. I'm having a 800Wh solar installation and can't make 8kWh.
![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/4629834/a05eb8fa-1ecd-404a-a24c-9ad8e1c374af)

It would be nice to get some hints how to correct setup HA displaying my data.

This is if I show the extension data on the dashboard.
![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/4629834/13d473f4-67a1-4d6f-8cdf-ae5a5ec82caa)

**Comment by suaveolent** [comment]
Your screenshot looks correct.
The first image shows the total number of kW/h for the time from 22.02.2024 - 26.02.2024 (see upper right corner).

So the 8.8kW/h are not for one day but for the entire week.

**Comment by ThomWee** [comment]
@suaveolent thanks for reply. I thought the view in the upper right corner are the actual values from right now, because of the nice animation.
When checking the history for AC daily energy, the board shows me that this value is always 0 or like in my second screenshot Unknown. Do I need to tweak something in the extension?

**Comment by saxn-paule** [comment]
It works if you use the daily AC Power:
![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/8352690/ba46cb90-0ea7-499d-9aea-329a2f0ce6a2)

![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/8352690/6effaae4-64d5-4eeb-8a87-57ce221ab82c)

**Comment by suaveolent** [comment]
> @suaveolent thanks for reply. I thought the view in the upper right corner are the actual values from right now, because of the nice animation. When checking the history for AC daily energy, the board shows me that this value is always 0 or like in my second screenshot Unknown. Do I need to tweak something in the extension?

To get the same animation for live data you can use the following plugin:
https://github.com/flixlix/power-flow-card-plus


Yes, I noticed that the power was 0 or unknown before. Are you running the latest version of the integration (v0.1.4)?


Can you maybe navigate to 
Settings > Devices & Services >  Hoymiles HMS-XXXXW-T2 > Hoymiles HMS-XXXXW-T2 

and see if the sensor "AC power" shows up (entity id should be sensor.hoymiles_hms_xxxxw_t2_ac_power)?

**Comment by ThomWee** [comment]
I can see this entity but no data are present, just 0. Can I somehow create logs or some printout helping to debug my problem?
![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/4629834/e78f0645-9e79-4166-9334-80c5758de9c1)

**Comment by ThomWee** [comment]
And yes I'm using 0.1.4

**Comment by suaveolent** [comment]
Are you familiar with CLI / python pip? 

You can try running the ´get-real-data-new` request from the underlying library itself. See:

https://github.com/suaveolent/hoymiles-wifi

e.g. 

`hoymiles-wifi --host <IP-Address or Hostname of DTU> get-real-data-new`

**Comment by ThomWee** [comment]
> Get-real-data-new Response: 
device_serial_number: "413******"
timestamp: 1709048682
active_power: 1
firmware_version: 1
sgs_data {
  serial_number: 189***************
  firmware_version: 1
  voltage: 2396
  frequency: 4996
  active_power: 168
  current: 7
  power_factor: 1000
  temperature: 98
  warning_number: 1
  crc_checksum: 4099
  link_status: 1
  modulation_index_signal: 2097182
}
pv_data {
  serial_number: 189************
  port_number: 1
  voltage: 412
  current: 21
  power: 89
  energy_total: 37325
  energy_daily: 229
  error_code: 50331648
}
pv_data {
  serial_number: 189***********
  port_number: 2
  voltage: 409
  current: 21
  power: 88
  energy_total: 34390
  energy_daily: 216
  error_code: 50331648
}

> Get-version-info Response: 
dtu_hw_version: "H06.02.01"
dtu_sw_version: "V00.03.12"
inverter_hw_version: "H00.04.00"
inverter_sw_version: "V01.00.02"

**Comment by suaveolent** [comment]
Thanks, It seems like you have a completely different HW/SW version than I have and the `dtu_power` is missing in your response. 

Have you already upgraded to latest DTU version (V00.01.11 for me)?

This might fix your problem. Otherwise I might also be able to fix it in a future update using the `active_power` of `sgs_data`.

**Comment by ThomWee** [comment]
Hmm, I updated my DTU now from SW version 00.03.12 to 00.03.13 ... now I get way less data 

> Get-real-data-new Response: 
device_serial_number: "4133A00323C2"
timestamp: 1709051117
active_power: 1
firmware_version: 1
sgs_data {
  serial_number: 18985986852358
  modulation_index_signal: 7929856
}
pv_data {
  serial_number: 18985986852358
  port_number: 1
}
pv_data {
  serial_number: 18985986852358
  port_number: 2
}

**Comment by suaveolent** [comment]
Thanks, seems like this info is not provided with your DTU. I will fix it with next version. 

Btw: Which inverter model do you have?

**Comment by ThomWee** [comment]
Thanks. I added the active_power sensor by hand now. Let's see tomorrow if there are data send to my HA sensors.

![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/4629834/e77caa27-58f5-40fd-b53a-b4eea5ad1d81)

**Comment by suaveolent** [comment]
Pushed fix to main, will be fixed with next release.
