### ISSUE TITLE
Translation to German

### ISSUE THREAD

**Issue by T4s-H4g** [suaveolent/ha-hoymiles-wifi#18]
Hi @suaveolent,
is it possible to translate your component to German? If it's easy I can do that. Have I do a pull request for the translation then? Or what's the way?

Best,
Thomas

**Comment by suaveolent** [comment]
Thanks @T4s-H4g, 

yes all you need to do is create a de.json file similar to the en.json file and create a pull request for it.

**Comment by suaveolent** [comment]
Fixed by #19.
