### ISSUE TITLE
Platform not found

### ISSUE THREAD

**Issue by Mal0815** [suaveolent/ha-hoymiles-wifi#20]
Hello and many thanks for this great software. Today, I've set up my 800w-2t. So far I was able to change network configuration to match my local network. I also installed the custom component via HACS on my HA Core. The integration shows up and connects to the device/ip. Unfortunately, there are errors that prevent any further interactions. I hope, you can help me. :) 
Regards, Mathias

The error:
Logger: homeassistant.setup
Source: setup.py:344
First occurred: 17:38:57 (4 occurrences)
Last logged: 17:38:57

Unable to prepare setup for platform hoymiles_wifi.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform hoymiles_wifi.binary_sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform hoymiles_wifi.number: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform hoymiles_wifi.button: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).

**Comment by suaveolent** [comment]
Are you running the latest version of home assistant? It seems you are running an old version where the device info was not available.

**Comment by Mal0815** [comment]
Good morning and thanks a lot. You are right. In fact, I checked for updates before, but HA doesn't show any available updates in the UI. Your hint made me think about it and yes, I currently run some 2023 version. So I have to solve this one first. Many thanks and have a great weekend!

**Comment by Mal0815** [comment]
All is running fine now. Thank you!

**Comment by suaveolent** [comment]
Great! Closing the issue then.
