### ISSUE TITLE
Wrong naming (or am I wrong?) HMS-XXXXW-T2 instead of HMS-XXXXW-2T

### ISSUE THREAD

**Issue by Chaosflo** [suaveolent/ha-hoymiles-wifi#23]
I noticed that the naming is inconsistent.
In GitHub everywhere at least what I could find was HMS-XXXXW-2T but in home assistant, hacs its HMS-XXXXW-T2.
Which I think atleast is wrong (the T and 2 are reversed)

Just a small little thing for my eye ^^
But thank u alot for the integration!

**Comment by Chaosflo** [comment]
Here 
https://github.com/suaveolent/ha-hoymiles-wifi/blob/54dd8454785725454d4eb95bdbc5c5d81e6438a5/hacs.json#L2C12-L2C33

https://github.com/suaveolent/ha-hoymiles-wifi/blob/54dd8454785725454d4eb95bdbc5c5d81e6438a5/custom_components/hoymiles_wifi/translations/en.json#L5

https://github.com/suaveolent/ha-hoymiles-wifi/blob/54dd8454785725454d4eb95bdbc5c5d81e6438a5/custom_components/hoymiles_wifi/translations/de.json#L5

https://github.com/suaveolent/ha-hoymiles-wifi/blob/54dd8454785725454d4eb95bdbc5c5d81e6438a5/custom_components/hoymiles_wifi/strings.json#L5

https://github.com/suaveolent/ha-hoymiles-wifi/blob/54dd8454785725454d4eb95bdbc5c5d81e6438a5/custom_components/hoymiles_wifi/entity.py#L32

https://github.com/suaveolent/ha-hoymiles-wifi/blob/54dd8454785725454d4eb95bdbc5c5d81e6438a5/custom_components/hoymiles_wifi/entity.py#L33

https://github.com/suaveolent/ha-hoymiles-wifi/blob/54dd8454785725454d4eb95bdbc5c5d81e6438a5/custom_components/hoymiles_wifi/const.py#L3

I hope I found every occurences =)

**Comment by suaveolent** [comment]
Thank you so much for your input.
I noticed that around 2 weeks ago. I am currently working on supporting more models (incl. DTU-Wlite).
There will be a new release shortly which not only includes the reanming from T2 to 2T but also adds support for detecting the correct model.

**Comment by Chaosflo** [comment]
Fine! 
Just a notice, if you rename it, be sure to post a breaking change, as the entities will be renamed too! 

![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/13841355/4c52ff39-be70-40b7-b329-56f63df60147)
This could then break much ^^
Just so that you have it on the table

**Comment by suaveolent** [comment]
> Fine! Just a notice, if you rename it, be sure to post a breaking change, as the entities will be renamed too!
> 
> ![image](https://private-user-images.githubusercontent.com/13841355/316462571-4c52ff39-be70-40b7-b329-56f63df60147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjI3MjcsIm5iZiI6MTcxMTM2MjQyNywicGF0aCI6Ii8xMzg0MTM1NS8zMTY0NjI1NzEtNGM1MmZmMzktYmU3MC00MGI3LWIzMjktNTZmNjNkZjYwMTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEwMjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZWU4N2E1YWQ1ZmFlMTE5ZDgyMmY1YjQ4YTcwMTMyMTZkMWZmZjFjYTMyN2NmNDgyMzU4MjI4MWRkNGE5MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MLXLdUiOKYZBG2zxPQFYNugwTvWPRjduOfWJIZAcWZ0) This could then break much ^^ Just so that you have it on the table

Thanks, already testing that feature. For updating, it seems that even though the device name changes, the entity name stays the same. Only if you do a fresh update, the entity id name seems to change. 

If you are feeling lucky or want to beta test, you can try manually updating to the `multi_inverter` branch. 
You should see two new devices, with the new names. 
The old devices will still be there, but you can manually delete them. (It was too much of a hassle to implement a correct migration strategy ;))

**Comment by suaveolent** [comment]
Closing with release of v0.2.0
