### ISSUE TITLE
Wrong power factor reading

### ISSUE THREAD

**Issue by Julian0021** [suaveolent/ha-hoymiles-wifi#27]
Some readings of the power factor are around 6000%. Using the latest available release of the integration.

![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/45150576/303fa5c7-eee5-46e5-a48f-b4f80512ec92)

**Comment by Julian0021** [comment]
> Are you still running your inverter with active firewall? Cannot reproduce the issue at the moment. 

No. Did nothing I am aware of that could be causing the issue

**Comment by suaveolent** [comment]
Can you run the `get-real-data-new` command of the `hoymiles-wifi` library to see what the DTU returns?

 https://github.com/suaveolent/hoymiles-wifi
