### ISSUE TITLE
AC Daily Energy was not reseted 

### ISSUE THREAD

**Issue by mbrockeu** [suaveolent/ha-hoymiles-wifi#3]
**Describe the bug**
The AC Energy for daily usage is not reset to 0 at the beginning of the day.

**To Reproduce**
1. Open sensor at the beginning of the day when the Inverter starts producing

**Expected behavior**
The value will be set to 0 if this is also the value in the app.

**Screenshots**
Screenshot was taken at 8:57 compared to app the values are not correct
<img width="474" alt="image" src="https://github.com/suaveolent/ha-hoymiles-wifi/assets/16849873/3d910233-7922-4fa0-8ff8-14e40c844605">

![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/16849873/b809ab0f-3828-4a43-9ee7-5c216a41e98f)

Version is 0.0.7

**Comment by mbrockeu** [comment]
Ok forget what I say, after 1 Wh is produced the correct value is shown ;-)

**Comment by suaveolent** [comment]
Great, closing this issue then.

**Comment by culixnet** [comment]
Had a similar effect: One day I accidentally reduced the AC output to 0% for a whole day -  HA then displayed and counted the Wh from the day before
