### ISSUE TITLE
DTU daily energy not working without internet

### ISSUE THREAD

**Issue by ftepegit** [suaveolent/ha-hoymiles-wifi#32]
**Describe the bug**
DTU daily energy does not update anymore and stays the same when internet connection is broken and reset to zero after DTU restart.

**To Reproduce**
1. Disconnect Internet from Router
2. Monitor DTU AC Daily Energy value (eg. 11:00-12:50 in Screenshot)
3. Restart DTU
4. Values are updated but reset to 0 to start from

**Expected behavior**
As local network is not affected, data should be read as usual.

**Screenshots**
![2024-04-24 15_02_07-Verlauf – Home Assistant und 4 weitere Seiten - Persönlich – Microsoft​ Edge](https://github.com/suaveolent/ha-hoymiles-wifi/assets/77061915/7ff5f38f-6aec-4c31-8910-f02c196d0241)

**Desktop (please complete the following information):**
Core 2024.4.4
Supervisor 2024.04.0
Operating System 12.2
Frontend 20240404.2
Hoymiles for Home Assistant v0.2.1
HMS-800W-2T:
DTU H00.01.00 / V00.01.11
Inverter H00.04.00 / V01.00.08

**Comment by suaveolent** [comment]
Could this be an issue with the DTU rather than the integration? 

As you said, it works fine after the DTU is restarted which makes me believe the inverter actually is not updating the data. 

It would also explain why the daily energy is reported as 0 afterwards because if it was related to the integration there would be a jump in the graph from 0 to the value previously reported.

**Comment by ftepegit** [comment]
Might be the case, but I don't know how I cloud fix this or see if it is related to the inverter. I've read in other issues that there are issues when Internet Access is blocked completely, was wondering if it might also cause this issue.

Is it possible to configure the integration that it continues to count the DTU AC Daily Energy instead of relying what the inverter reports? Does your inverter also Report 0 Wh AC Daily Energy produced after a reboot?

**Comment by suaveolent** [comment]
No the Inverter keeps the same ac daily energy (while connected to Internet).

I did not yet test whether this changes if I disable Internet access.
