### ISSUE TITLE
Only 4/5 inverters show up

### ISSUE THREAD

**Issue by Pasimk** [suaveolent/ha-hoymiles-wifi#33]
Installation found only 4 of my 5 hms-1800 inverters - which are showing as 1600-T models.

**Comment by suaveolent** [comment]
Thanks, @LuucA80 has experienced a similar issue.

It seems that the DTU does not report back all inverters to some reason. 
Can you maybe run the `get-real-data-new` command from the https://github.com/suaveolent/hoymiles-wifi library?

**Comment by Pasimk** [comment]
Get-real-data-new Response: 
device_serial_number: "10FD8*"
timestamp: 1714052000
active_power: 2
firmware_version: 1
sgs_data {
  serial_number: 191233*
  firmware_version: 1
  voltage: 2297
  frequency: 5001
  active_power: 1740
  reactive_power: 1
  current: 75
  power_factor: 999
  temperature: 105
  warning_number: 808
  crc_checksum: 48367
  link_status: 1
  modulation_index_signal: 11730975
}
sgs_data {
  serial_number: 191233*
  firmware_version: 1
  voltage: 2300
  frequency: 5001
  active_power: 1775
  reactive_power: 1
  current: 77
  power_factor: 999
  temperature: 96
  warning_number: 808
  crc_checksum: 28864
  link_status: 1
  modulation_index_signal: 14090269
}
sgs_data {
  serial_number: 19123*
  firmware_version: 1
  voltage: 2306
  frequency: 5001
  active_power: 1738
  reactive_power: 1
  current: 75
  power_factor: 999
  temperature: 90
  warning_number: 799
  crc_checksum: 19828
  link_status: 1
  modulation_index_signal: 15007842
}
sgs_data {
  serial_number: 19123*
  firmware_version: 1
  voltage: 2315
  frequency: 5001
  active_power: 1744
  current: 75
  power_factor: 1000
  temperature: 86
  warning_number: 801
  crc_checksum: 11439
  link_status: 1
  modulation_index_signal: 7864530
}
pv_data {
  serial_number: 1912339*
  port_number: 1
  voltage: 318
  current: 142
  power: 454
  energy_total: 108042
  energy_daily: 575
  error_code: 50921472
}
pv_data {
  serial_number: 19123*
  port_number: 2
  voltage: 316
  current: 142
  power: 451
  energy_total: 107371
  energy_daily: 575
  error_code: 50331648
}
pv_data {
  serial_number: 191233*
  port_number: 3
  voltage: 319
  current: 145
  power: 463
  energy_total: 109968
  energy_daily: 583
  error_code: 50331648
}
pv_data {
  serial_number: 191233*
  port_number: 4
  voltage: 319
  current: 144
  power: 461
  energy_total: 113192
  energy_daily: 581
  error_code: 50331648
}
pv_data {
  serial_number: 19123*
  port_number: 1
  voltage: 319
  current: 144
  power: 463
  energy_total: 110650
  energy_daily: 582
  error_code: 50331648
}
pv_data {
  serial_number: 191233*
  port_number: 2
  voltage: 320
  current: 145
  power: 467
  energy_total: 106762
  energy_daily: 588
  error_code: 50331648
}
pv_data {
  serial_number: 1912339*
  port_number: 3
  voltage: 318
  current: 146
  power: 467
  energy_total: 102176
  energy_daily: 588
  error_code: 50331648
}
pv_data {
  serial_number: 191233*
  port_number: 4
  voltage: 320
  current: 147
  power: 470
  energy_total: 106270
  energy_daily: 591
  error_code: 50331648
}
pv_data {
  serial_number: 191233*
  port_number: 1
  voltage: 319
  current: 143
  power: 458
  energy_total: 99946
  energy_daily: 584
  error_code: 50921472
}
pv_data {
  serial_number: 191233*
  port_number: 2
  voltage: 319
  current: 143
  power: 457
  energy_total: 96487
  energy_daily: 584
  error_code: 50331648
}
pv_data {
  serial_number: 1912339*
  port_number: 3
  voltage: 318
  current: 142
  power: 454
  energy_total: 93887
  energy_daily: 580
  error_code: 50331648
}
pv_data {
  serial_number: 191233*
  port_number: 4
  voltage: 319
  current: 143
  power: 458
  energy_total: 95131
  energy_daily: 585
  error_code: 50331648
}
pv_data {
  serial_number: 191233*
  port_number: 1
  voltage: 319
  current: 143
  power: 459
  energy_total: 108323
  energy_daily: 582
  error_code: 50921472
}
pv_data {
  serial_number: 1912339*
  port_number: 2
  voltage: 319
  current: 144
  power: 460
  energy_total: 110977
  energy_daily: 583
  error_code: 50331648
}
pv_data {
  serial_number: 191233*
  port_number: 3
  voltage: 319
  current: 144
  power: 460
  energy_total: 108499
  energy_daily: 585
  error_code: 50331648
}
pv_data {
  serial_number: 191233*
  port_number: 4
  voltage: 318
  current: 143
  power: 455
  energy_total: 107760
  energy_daily: 580
  error_code: 50331648
}
dtu_power: 8745
dtu_daily_energy: 11649

**Comment by suaveolent** [comment]
Thanks, that is exactly what I thought it would look like: `sgs_data` describes the connected inverters. And only 4 of them are reported back by the command.

Can you maybe also run the `get-real-data` and `app-information-data` to see if the remaining inverter shows up somewhere else?

If not, I fear there is nothing really I can do, except maybe ask hoymiles directly why the 5th inverter is not reported.

**Comment by suaveolent** [comment]
@Pasimk  I also noticed that the DTU serial `10FD...` is not currently listed in my mapping. Which DTU do you have?

**Comment by Pasimk** [comment]
Dtu-pro-s suaveolent ***@***.***> kirjoitti 26.4.2024 kello 12.19:﻿
@Pasimk  I also noticed that the DTU serial 10FD... is not currently listed in my mapping. Which DTU do you have?

**Comment by Pasimk** [comment]
HiApp-information-data lists all 5 inverters, get-real-data only 4.Pasisuaveolent ***@***.***> kirjoitti 26.4.2024 kello 12.15:﻿
Thanks, that is exactly what I thought it would look like: sgs_data describes the connected inverters. And only 4 of them are reported back by the command.
Can you maybe also run the get-real-data and app-information-data to see if the remaining inverter shows up somewhere else?
If not, I fear there is nothing really I can do, except maybe ask hoymiles directly why the 5th inverter is not reported.

**Comment by suaveolent** [comment]
Thanks. In that case, I probably could add the 5th inverter, but it will not show any data since `get-real-data` does not report anything. Might be a limitation of the DTU? 

I will leave the issue open for now. Maybe I can find something to force the DTU to report all inverters.
