### ISSUE TITLE
Question: Setup with Cloud Connection

### ISSUE THREAD

**Issue by MuellerNicolas** [suaveolent/ha-hoymiles-wifi#34]
Hello @suaveolent ,
thank you very much for this integration 🤩 I have a question regarding the Hoymiles HMS-800W-2T: My dad is interacting with the inverter offline via the hoymiles app. I'm thinking about using your integration, but disabling the internet connection of the inverter on the router (FritzBox) after the setup (seems possible for some, according to #32).

Now my question: If something in the progress fails - can I reset the device, so that my dad can interact with the device via the app as an unregistered user (connection between the inverter and the app directly [without the cloud]) just like before?

Is there any possiblity to reset it back to factory settings?

Thank you very much in advance 😊

**Comment by suaveolent** [comment]
Yes, reset should be possible: have a look in the manual section 6.3.
