### ISSUE TITLE
Can't connect to host

### ISSUE THREAD

**Issue by HASolace** [suaveolent/ha-hoymiles-wifi#36]
I'm running HA as a container and constantly run into the following error when trying to connect to my HMS-800W-2T.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 4. Mai 2024 um 00:04:57 (1 occurrences)
Last logged: 4. Mai 2024 um 00:04:57

Error adding entities for domain sensor with platform hoymiles_wifi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'translation_key'

**Comment by suaveolent** [comment]
Please update your Home Assistant version. The error indicates that you are running an old version of Home Assistant.

**Comment by suaveolent** [comment]
Either the ip address or the host name (dns name)

**Comment by suaveolent** [comment]
Is there anything in the logs which might explain the error?

**Comment by ShaneFK95111** [comment]
What do I have to use for host? Cant connect…:-(

**Comment by suaveolent** [comment]
> What do I have to use for host? Cant connect…:-(

Either the ip address or the host name (dns name)...

**Comment by ShaneFK95111** [comment]
> > What do I have to use for host? Cant connect…:-(
> 
> Either the ip address or the host name (dns name)...

Yeah thanks, Bit which device IP? Of hoymiles converter?

**Comment by suaveolent** [comment]
> > > What do I have to use for host? Cant connect…:-(
> > 
> > 
> > Either the ip address or the host name (dns name)...
> 
> Yeah thanks, Bit which device IP? Of hoymiles converter?

Yes.

**Comment by maartentmm** [comment]
Im up to date and can't connect to host

Core
2024.5.3
Supervisor
2024.05.1
Operating System
12.3
Frontend
20240501.1

**Comment by suaveolent** [comment]
Is there anything in the log? 

Can you ping the inverter from your home assistant instance?

**Comment by maartentmm** [comment]
> Is there anything in the log?
> 
> Can you ping the inverter from your home assistant instance?

Yes i get pings without timeout.

**Comment by suaveolent** [comment]
Can you maybe enable debug logging for the hoymiles-wifi integration and check if there is anything in the logs which might explain the issue?

**Comment by maartentmm** [comment]
> Can you maybe enable debug logging for the hoymiles-wifi integration and check if there is anything in the logs which might explain the issue?

its working now with the ethernet disconnected
