### ISSUE TITLE
Update 0.2.2 causes energy dashboard to break 

### ISSUE THREAD

**Issue by N3rdix** [suaveolent/ha-hoymiles-wifi#37]
**Describe the bug**
Although it is mentioned in the code that the new workaround for #32 should handle zero values correctly it seems to break something.
I have updated to 0.2.2 yesterday and now the total energy sensors jump to zero at night and jump back to the original value when the DTU starts at morning. This of course leads to incorrect solar production values as in my example.

**To Reproduce**
1. Update to 0.2.2
2. Add the total energy sensors to the energy dashboard
3. See error

**Expected behavior**
The total energy sensors should not reset to zero at all.

**Screenshots**
<img width="462" alt="image" src="https://github.com/suaveolent/ha-hoymiles-wifi/assets/70015952/df7f4b58-0890-4ec2-b94c-c3f5821bea6d">
<img width="462" alt="image" src="https://github.com/suaveolent/ha-hoymiles-wifi/assets/70015952/59a23316-4d7d-476b-a14e-32be252ac454">
<img width="462" alt="image" src="https://github.com/suaveolent/ha-hoymiles-wifi/assets/70015952/19f4d067-36be-4585-9b7c-3d4e5d5a001b">

**Additional context**
Temporary workaround can be to delete the outlier values every day, so at least nothing will break hard 😄

**Comment by suaveolent** [comment]
Thanks, you are right. Will provide a fix later today.

**Comment by suaveolent** [comment]
One more comment: you should not use total energy for the energy dashboard. 

If you restart your home assistant instance and the inverter is not available it might return 0 anyway.

Instead use daily energy. It works just as intented even if the sensor is set to 0.

**Comment by N3rdix** [comment]
> One more comment: you should not use total energy for the energy dashboard.
> 
> If you restart your home assistant instance and the inverter is not available it might return 0 anyway.
> 
> Instead use daily energy. It works just as intented even if the sensor is set to 0.

Thanks for that hint, will look into this although I did not have any trouble yet (luckily). Historically I've added total sensors the past years, but according to the HA docs your advice might be the best choice 👍

**Comment by suaveolent** [comment]
`v0.2.3` should fix the problem.

**Comment by N3rdix** [comment]
Thanks for the quick resolution, awesome work 👏

**Comment by suaveolent** [comment]
You‘re welcome. With the fix you should be able to keep using the total sensor.
