### ISSUE TITLE
Sensor prefix is not applied

### ISSUE THREAD

**Issue by mbrockeu** [suaveolent/ha-hoymiles-wifi#4]
**Describe the bug**
I set a sensor prefix because I have 2 inverters. The prefix is not used. The naming only add a _2 behind all sensors. Which is not very useful by searching for an inverter

**To Reproduce**
1. Create new configuration, set IP and prefix

**Expected behavior**
the defined prefix should be applied

**Screenshots**

**Comment by suaveolent** [comment]
Should be fixed in v.0.0.9
