### ISSUE TITLE
Bug fetching the DTU meter kind

### ISSUE THREAD

**Issue by elafontaine** [suaveolent/ha-hoymiles-wifi#40]
**Describe the bug**
The connection between HA and the DTU seems to drop every 5 minutes, while this is also a separate issue, I noticed that it also changed the DTU meter kind by adding a random character at the end.

**To Reproduce**
1. Go to logbook
2. Look at the DTU entries that change values

**Expected behavior**
No change to the meter kind should change if it didn't change

**Screenshots**
![Screenshot_20240529_142410_Home Assistant](https://github.com/suaveolent/ha-hoymiles-wifi/assets/3026004/5a8b29a7-c2da-40bb-820f-feb7a3235ce3)

**Additional context**

**Comment by elafontaine** [comment]
Another capture about the DTU status in HA
![Screenshot_20240529_142520_Home Assistant](https://github.com/suaveolent/ha-hoymiles-wifi/assets/3026004/0a508286-b4ff-4ab9-8eae-365cb759df85)

**Comment by suaveolent** [comment]
Are you running your DTU in offline mode (e.g. blocked via Router / Firewall) ?

**Comment by elafontaine** [comment]
I do not know what this means, but the DTU is reporting it's data to S-miles Cloud.  So I would assume it isn't in "offline" mode.

**Comment by suaveolent** [comment]
I see. I was asking since the Hoymiles W-series has a similar issue when access to the Internet is blocked.

What is weird: I have implemented the CRC check in the library, so in my opinion these are the values the DTU transmits. Otherwise, there would be an error. However, I did not have a closer look yet.

I guess that you are already running the latest firmware of the DTU?

**Comment by elafontaine** [comment]
Yes, and my guess is that there must be a single byte to much in the string...

**Comment by elafontaine** [comment]
turns out I wasn't.  I was expecting the mobile application would had told me, but turns out it doesn't even suggest it even on the main s-miles pages  !  I updated to the latest (2.23) and that solved the issues.  So sorry for the noise.

![image](https://github.com/suaveolent/ha-hoymiles-wifi/assets/3026004/09e0b74a-e5cb-465c-ad2e-0c5eebac3fd3)

**Comment by suaveolent** [comment]
Great, thanks for letting me know.
