### ISSUE TITLE
Name of Inverter is wrong

### ISSUE THREAD

**Issue by ShadowJumper** [suaveolent/ha-hoymiles-wifi#41]
**Describe the bug**
When i´m add a HMS-1000W-2T, in HA it shows as HMS-800W-2T 

**To Reproduce**
Add an HMS-1000W-2T

**Screenshots**
![2024-06-03 21_18_37-Einstellungen – Home Assistant](https://github.com/suaveolent/ha-hoymiles-wifi/assets/1102805/a710f655-8ed3-422d-9a13-d17f8fa65622)
![2024-06-03 21_19_46-S-Miles Cloud - Hoymiles Power Electronics Inc](https://github.com/suaveolent/ha-hoymiles-wifi/assets/1102805/5797f1dc-38ce-41a6-ba17-a6be05777190)

**Comment by suaveolent** [comment]
Thanks for reporting.
I try to retrieve the inverter model via the serial. Can you maybe post the first 6 digits of your serial number?

**Comment by ShadowJumper** [comment]
Yes, this was the 141293

**Comment by suaveolent** [comment]
Great. Does the Serial of your 800W-2T by any change start with `141292` ? If so I could distinguish between these two models.

**Comment by ShadowJumper** [comment]
Hi, yes, on my 800W-2T the serial starts with 141292.

**Comment by suaveolent** [comment]
Great, so I can distinguish between those two models.

**Comment by ShadowJumper** [comment]
I test your new version, and it works, but you have a typo in it -> ['HMS-10000W-2T'] instead of ['HMS-1000W-2T'].

**Comment by suaveolent** [comment]
Thanks! Fixed that now. I will most likely push a new version this week and afterwards close this issue.
