### ISSUE TITLE
Using a switch instead of buttons for turn on and off

### ISSUE THREAD

**Issue by phiten** [suaveolent/ha-hoymiles-wifi#42]
**Is your feature request related to a problem? Please describe.**
Not really a problem but an inconvenience when creating automations. Having a state if the inverter is tuned on or off is sometimes  required for some logic. Like only setting the power limit when it is actually in use.

**Describe the solution you'd like**
Instead of having two buttons have one switch controlling the state of the inverter. 

**Describe alternatives you've considered**
Another solution would be having an additional variable showing the state of the inverter.

**Additional context**

**Comment by suaveolent** [comment]
Seems like a good idea. I need to find out a reliable way though to check the status of the inverter.
