### ISSUE TITLE
Get no entities after install 

### ISSUE THREAD

**Issue by Malcolm2203** [suaveolent/ha-hoymiles-wifi#46]
Hello I get no entities after install these are the logs....

Unable to prepare setup for platform hoymiles_wifi.sensor: Platform not found (Exception importing custom_components.hoymiles_wifi.sensor).
10:01:24 – (FEHLER) setup.py - Die Nachricht ist zum ersten Mal am 10:01:24 aufgetreten und erscheint 4 mal
Unexpected exception importing platform custom_components.hoymiles_wifi.sensor
10:01:24 – (FEHLER) loader.py - Die Nachricht ist zum ersten Mal am 10:01:24 aufgetreten und erscheint 4 mal

thank you

**Comment by suaveolent** [comment]
Are you running the latest version of home assistant?

https://github.com/suaveolent/ha-hoymiles-wifi/issues/29
See also: https://github.com/suaveolent/ha-hoymiles-wifi/issues/38
