### ISSUE TITLE
EoF error in strings.json

### ISSUE THREAD

**Issue by Sonnenwerk** [suaveolent/ha-hoymiles-wifi#48]
**Describe the bug**
An error with eofile. Unsure if it´s just indentation or not.
Seen it on 2.4dev in strings.json

<img width="356" alt="image" src="https://github.com/user-attachments/assets/4196a8e8-bb05-443d-988c-bc69cd3f413a">

**Comment by suaveolent** [comment]
@Sonnenwerk thanks, just deleted the old dev and pusht a new version `0.2.4-dev` that should fix the issue.

**Comment by Sonnenwerk** [comment]
reinstalled. gone ! Top !

**Comment by suaveolent** [comment]
Great, closing the issue then.
