### ISSUE TITLE
Since the update not 100% Power as usually before

### ISSUE THREAD

**Issue by casionline** [suaveolent/ha-hoymiles-wifi#52]
Hi, since the update some days ago, i see, that my hoymiles hms-800w-2t hasnt peak 810Watt but 430Watt, what is only the power of 1 panel.
I restarted the hoymiles using the original smiles app. From that point i have nearly 700Watt. I checked the max power setting, its on 100%.

Its same on mobile home assistant and using Desktop with firefox.
All updates on my homeassistant, mobile or desktop pc are installed....

Im pretty noob in all this but before the update everything was up and running without any issues...
If i can provide any log or missing data, please tell my.

Thanks so much for this plugin.

Casi

**Comment by suaveolent** [comment]
Hi,

Thanks for reporting. However, the plugin should not have any impacts on your inverter. Esp. with the last update since there were not any changes in that direction.

I also do not see such a behaviour with my inverter.

What sensor are you comparing? AC power?

**Comment by casionline** [comment]
Hi, Thanks for the fast answer. Yes AC Power, the total should be around 800, as fast i Can see, it looks like locked around 700 Watt, what looks like the old maximum allowed....

06.08.2024 15:36:38 suaveolent ***@***.***>:

**Comment by casionline** [comment]
Can i downgrade to the previous Version? How?

06.08.2024 15:36:38 suaveolent ***@***.***>:

**Comment by suaveolent** [comment]
Yes, you can downgrade via HACS, just click "Redownload" and select an older version.

Let me know if that fixes the issue so that I can investigate.

**Comment by casionline** [comment]
Ok, cool. I downloaded and will check the next Day when theres enough sunshine. I let you know.

06.08.2024 17:38:13 suaveolent ***@***.***>:

**Comment by suaveolent** [comment]
[casionline](https://github.com/casionline) Any news?

**Comment by casionline** [comment]
Hi, i had only some time to do testing. I find out, its perhaps a problem in the firmware or the microinverter, when i restarted with the orig app, it works again with Füll power instead the 50% lock... I wrote to hoymiles and send them screenshots, hope to hear from them. Ill contact the dealer Here today by phone and aak of this behaviour is know, ill give you feedback whe hearing news. See the picture, it shows the restart at the right side, effecting the power. Thanks. Casi

12.08.2024 08:10:36 suaveolent ***@***.***>:

**Comment by lxk478** [comment]
I had a similar behaviour today,
(Hoymiles DTU-WLite-S  + Hoymiles HMS-1600-4T)
the output power was limited to ca. 750 Watt.
i found the following in the log:
            number.wechselrichter_leistungsbegrenzung 0.0
            01:57:04 - Vor 11 Stunden
Which is strange, because the wechselrichter is off at night with no sunshine.
I switched it back to 100 in Home Assistant and the ac-power was back to max (1530W at this moment)
I deactivated this entity (don't know if it helps).
One minute before this log entry was another entry in the log
          Forecast Home wechselte zu Bewölkt
          01:56:05 - Vor 12 Stunden

**Comment by lxk478** [comment]
The same today,
i didnt't disable/deactivate the "leistungsbegrenzung"

"number.wechselrichter_leistungsbegrenzung
wechselte zu 0,0
01:57:19 - Vor 12 Stunden"

This specific time is close to UTC 00:00   (German summer time is UTC +2 hours), Maybe it is a mislead automatic reset of 
sensor.dtu_ac_tagesenergie at midnight?
This entity doesnt work in my setup (Hoymiles DTU-WLite-S + Hoymiles HMS-1600-4T). At first it was unknown/invalid and after the first night it is 0.0 Wh permanently.

On the other hand, sun down in China these days is 18:57  and the reset happens after x hours in Germany.
Also the inverter (wechselrichter) seems to be limited to  800W/50%  (which is the officially allowed value  in Germany and 50% of its 1600W)
Changing the parameter back from 0 to 100 in Home Assistant doesnt affect the power of the inverter. I had to use the Hoymiles Installer App. In this App the displayed limit was 100%, i just press save and the inverter uses 100% of its power again. (today bright blue sky at 09:45 am the power went from 440Watts to 770Watts)

**Comment by casionline** [comment]
Fter restarting DTU and microinverter several times in HA and the Smiles App, over  i think 1 hour, it works again at 100% , dont know exactly what finnaly helps, but after a while its ok. But, i had to do something, and i have to notice it on my own...

**Comment by casionline** [comment]
![dtu loss](https://github.com/user-attachments/assets/58f87214-1ecd-4ebe-acad-366a5668399f)
