### ISSUE TITLE
Second inverter has missing entities

### ISSUE THREAD

**Issue by christof62** [suaveolent/ha-hoymiles-wifi#58]
A DTU-Lite-S is used to connect to 2 identical HMT-2250-6T inverters. The second identified inverter has an incomplete list of entities as there are no entities for port 3 - 6. The total number of created entities is 75.
This behaviour is reproducable with each configuration attempt.

Here the entities of the second inverter:
![image](https://github.com/user-attachments/assets/edc66d76-177c-4092-bd1d-d2a3f9720037)

And here the first inverter:
![image](https://github.com/user-attachments/assets/9016be7d-9d40-451d-b4a2-0bae477d4b28)

**Comment by suaveolent** [comment]
Thanks, this seems like a similar problem as 

https://github.com/suaveolent/ha-hoymiles-wifi/issues/51

I have not yet figured out why that is. 
Do you have access to the s miles installer app and are you able to capture network traffic via wireshark?

**Comment by christof62** [comment]
> Do you have access to the s miles installer app and are you able to capture network traffic via wireshark?

Yes, but unfortunately not now. This will be possible in about 2 weeks. I am not in the same network as the DTU.

**Comment by suaveolent** [comment]
That’s great. Maybe you can capture the network traffic sent by the phone to see what is different. I assume you get live data of all your inverters in the app.

**Comment by suaveolent** [comment]
Fixed in `v0.3.3`
