### ISSUE TITLE
No way to change IP address 

### ISSUE THREAD

**Issue by thomasbindl** [suaveolent/ha-hoymiles-wifi#61]
Since moving to a different Router the IP subnet changed and unfortunately I have to change the IP from 192.168.2.11 to 192.168.1.11, which is currently not possible, since the IP address can't be changed. 

When adding it as new entry, I get:
<img width="365" alt="image" src="https://github.com/user-attachments/assets/f539b4a8-4609-4b55-a541-14577014f387">

**Comment by suaveolent** [comment]
Thanks, reconfiguring the ip address is already on the roadmap.

In the meantime you can navigate to `/.homeassistant/.storage/` and manually edit the `core.config_entries` to change the ip address.

**Comment by suaveolent** [comment]
@thomasbindl I have just added support to Reconfigure the config entry.

Can you update to `main` branch to test if the feature works for you? You then need to click on the three dots next to the config entry and select "Reconfigure".

**Comment by suaveolent** [comment]
Closing with release of `v0.2.5`
