### ISSUE TITLE
HMS-xxxx-4T

### ISSUE THREAD

**Issue by SchaichaD** [suaveolent/ha-hoymiles-wifi#71]
**Is your feature request related to a problem? Please describe.**
This microinverter has 4 ports.

**Describe the solution you'd like**
Is it possible to get the values from all 4 ports?

**Comment by suaveolent** [comment]
It depends. In theory it should already work with 4 ports. 

Can you paste the output from the `get-real-data-new` command from the https://github.com/suaveolent/hoymiles-wifi lib? 

Please only keep the first 4 digits of the serial numbers.

**Comment by SchaichaD** [comment]
Sorry, but where can I find the file in my homeassitant installation  „Can you paste the output from the get-real-data-new command from the https://github.com/suaveolent/hoymiles-wifi lib?“?

Von: suaveolent ***@***.***>
Gesendet: Dienstag, 8. Oktober 2024 06:25
An: suaveolent/ha-hoymiles-wifi ***@***.***>
Cc: SchaichaD ***@***.***>; Author ***@***.***>
Betreff: Re: [suaveolent/ha-hoymiles-wifi] HMS-xxxx-4T (Issue #71)


It depends. In theory it should already work with 4 ports.

Can you paste the output from the get-real-data-new command from the https://github.com/suaveolent/hoymiles-wifi lib?

Please only keep the first 4 digits of the serial numbers.

**Comment by suaveolent** [comment]
You either need to install the tool as described in the readme or run the command from within your home assistant installation (beware if you are using a venv you need to activate it first).

**Comment by SchaichaD** [comment]
Sorry, but I am a beginner. I don´t know, where I can find the needed output.
I installed the hoymiles-wifi with hacs and it works. But I have a Hoymiles HMS2000-4T and I only get values for 2 ports. I would like to get the values for all 4 ports.
![hoymiles](https://github.com/user-attachments/assets/029fd658-d6a1-4b09-913a-d1f830865082)

**Comment by suaveolent** [comment]
Alright. In principle the component supports any number of ports.

The reason I need the response from the program is that I need to check why those ports are not showing up.

I assume this is a similar issue as https://github.com/suaveolent/ha-hoymiles-wifi/issues/51 and https://github.com/suaveolent/ha-hoymiles-wifi/issues/58.

In this case the DTU does not report back all the Ports. However, I have not yet found out why.

**Comment by Bernd-Reibeholz** [comment]
Hello,
I have a problem with a Hoymiles integration. I have six HM-1500 WRs on a dtu-pro, all of which are found by HA. All entities of the first two are transmitted, with the third only about half of them and then fewer and fewer of the other WRs...
Among other things, the entity AC daily energy is transmitted by the DTU, but its value is permanently "0 kWh". The current production of the WRs is also occasionally displayed as "0".
Everything is transferred correctly to the HoymilesCloud. The DTU is in the attic right next to the WRs and the connection between the DTU and the WiFi is very good with over 50% signal strength.
Does anyone have an idea?

**Comment by suaveolent** [comment]
See #51 i am working on a fix for that thanks to https://github.com/Toutatis64

**Comment by Bernd-Reibeholz** [comment]
Proüably that might help

 

2024-11-21 22:34:28.568 ERROR (MainThread) [homeassistant.components.number] Platform hoymiles_wifi does not generate unique IDs. ID hoymiles_01JCJBXBA9G68NGJZAKA3ZSSED_limit_power_mypower already exists - ignoring number.wechselrichter_leistungsbegrenzung

2024-11-21 22:34:28.568 ERROR (MainThread) [homeassistant.components.number] Platform hoymiles_wifi does not generate unique IDs. ID hoymiles_01JCJBXBA9G68NGJZAKA3ZSSED_limit_power_mypower already exists - ignoring number.wechselrichter_leistungsbegrenzung

2024-11-21 22:34:28.568 ERROR (MainThread) [homeassistant.components.number] Platform hoymiles_wifi does not generate unique IDs. ID hoymiles_01JCJBXBA9G68NGJZAKA3ZSSED_limit_power_mypower already exists - ignoring number.wechselrichter_leistungsbegrenzung

2024-11-21 22:34:28.569 ERROR (MainThread) [homeassistant.components.number] Platform hoymiles_wifi does not generate unique IDs. ID hoymiles_01JCJBXBA9G68NGJZAKA3ZSSED_limit_power_mypower already exists - ignoring number.wechselrichter_leistungsbegrenzung

2024-11-21 22:34:28.569 ERROR (MainThread) [homeassistant.components.number] Platform hoymiles_wifi does not generate unique IDs. ID hoymiles_01JCJBXBA9G68NGJZAKA3ZSSED_limit_power_mypower already exists - ignoring number.wechselrichter_leistungsbegrenzung

 

Von: suaveolent ***@***.***> 
Gesendet: Donnerstag, 14. November 2024 06:06
An: suaveolent/ha-hoymiles-wifi ***@***.***>
Cc: Bernd-Reibeholz ***@***.***>; Comment ***@***.***>
Betreff: Re: [suaveolent/ha-hoymiles-wifi] HMS-xxxx-4T (Issue #71)

 

See #51 <https://github.com/suaveolent/ha-hoymiles-wifi/issues/51>  i am working on a fix for that thanks to https://github.com/Toutatis64

**Comment by suaveolent** [comment]
@Bernd-Reibeholz 

Thanks, that is a different error which should not be related but needs to be fixed.

If you update to `main` branch, do you still don't see all entities?

**Comment by Bernd-Reibeholz** [comment]
Sorry, I am a newbee in HA and english.

I just deletet the Intergration and installed it again, there is no difference form e.

What do you mean with „update to main branch“?

 

Best Regards from Berlin (Germany)

Bernd

 

Von: suaveolent ***@***.***> 
Gesendet: Freitag, 22. November 2024 14:07
An: suaveolent/ha-hoymiles-wifi ***@***.***>
Cc: Bernd-Reibeholz ***@***.***>; Mention ***@***.***>
Betreff: Re: [suaveolent/ha-hoymiles-wifi] HMS-xxxx-4T (Issue #71)

 

@Bernd-Reibeholz <https://github.com/Bernd-Reibeholz> 

Thanks, that is a different error which should not be related but needs to be fixed.

If you update to main branch, do you still don't see all entities?

**Comment by suaveolent** [comment]
Fixed in `v0.3.3`

**Comment by Bernd-Reibeholz** [comment]
Hallo, it did not work at the first time, but whe I put up the time-intervall to 120 seconds I think, I got all entrys. Reconfigure with 30 secsnds worked aswell and now I pur it to 45 senconds and keep watching it with my 6 pieces of HM1500 on a dtu-Pro

 

Thanks a lot

 

Bernd

 

Von: suaveolent ***@***.***> 
Gesendet: Freitag, 6. Dezember 2024 16:22
An: suaveolent/ha-hoymiles-wifi ***@***.***>
Cc: Bernd-Reibeholz ***@***.***>; Mention ***@***.***>
Betreff: Re: [suaveolent/ha-hoymiles-wifi] HMS-xxxx-4T (Issue #71)

 

Closed #71 <https://github.com/suaveolent/ha-hoymiles-wifi/issues/71>  as completed.

**Comment by suaveolent** [comment]
Great, thanks for letting me know. 

I think by changing the update interval you automatically triggered the necessary reconfigure step which would query for all inverters against
