### ISSUE TITLE
What is this value

### ISSUE THREAD

**Issue by PiyaRawing** [suaveolent/ha-hoymiles-wifi#74]
- **Ha hoymiles v.0.3.1**

What are the values ​​of Phase A power and Phase total power? Or are they the values ​​of the phase a load current?

![image](https://github.com/user-attachments/assets/550e7269-8178-43a1-a845-44ba73dddc2f)

**Comment by suaveolent** [comment]
This is the power value of the phase the meter is connected to. There might be a conversion error though. What values is your meter reporting ? 
the reason why there is a phase total power is because some meters provide information about all three phases.

**Comment by PiyaRawing** [comment]
My DDSU666 meter has the following report values ​​compared to the data shown in home assistant. I am not sure if it is correct.

![image](https://github.com/user-attachments/assets/ae8ab0f3-7b9a-4291-81e9-3fca6e48245b)

![image](https://github.com/user-attachments/assets/5ce1716a-8866-4893-a8c1-6b20a955b457)

**Comment by suaveolent** [comment]
Thanks, that helps a lot. I will adjust the values accordingly.

**Comment by suaveolent** [comment]
Fixed in `v0.3.3`
