### ISSUE TITLE
deprecated alias which will be removed in HA Core 2025.11

### ISSUE THREAD

**Issue by nicolasglg** [suaveolent/ha-hoymiles-wifi#79]
Enregistreur: homeassistant.core
Source: helpers/deprecation.py:222
S'est produit pour la première fois: 09:10:35 (1 occurrences)
Dernier enregistrement: 09:10:35

Config was used from hoymiles_wifi, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'hoymiles_wifi' custom integration

**Comment by suaveolent** [comment]
Thanks for reporting. This should already be fixed with `v0.3.2`.

**Comment by nicolasglg** [comment]
Thanks for your hard work !

--
Nicolas



De : suaveolent ***@***.***>
Date : mardi, 19 novembre 2024 à 09:23
À : suaveolent/ha-hoymiles-wifi ***@***.***>
Cc : nicolasglg ***@***.***>, Author ***@***.***>
Objet : Re: [suaveolent/ha-hoymiles-wifi] deprecated alias which will be removed in HA Core 2025.11 (Issue #79)

Thanks for reporting. This should already be fixed with v0.3.2.
