### ISSUE TITLE
Cannot add custom repo

### ISSUE THREAD

**Issue by marcelK0** [suaveolent/ha-hoymiles-wifi#8]
**Describe the bug**
When I'm adding the custom repo according to the docs I get in _Installation Step 4_:

_No RepositoryFile.MAINIFEST_JSON file found 'custom_components/hoymiles_wifi/RepositoryFile.MAINIFEST_JSON'_

popup at the top of the custom repo list

**To Reproduce**
As described in the readme of the repo, happens in step 4

**Expected behavior**
Custom repo to be added from github

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Safari
 - HA: 2024.1.3
 - HA Host: ODROID

**Comment by suaveolent** [comment]
I tried with latest and home assistant core and could not reproduce the issue. Can you maybe provide some more log information from HACS install process?

**Comment by marcelK0** [comment]
ok, looks like HACS needed an update. Might be worth mentioning, as HACS is never updated unless you manually run the installer from the terminal again. It seems versions from 2022 are broken with today's HA.
Also some instructions on your doc are outdated, eg. step 5, it never asks to 'save' or 'install', but 'download', etc.
cheers

**Comment by marcelK0** [comment]
solved

**Comment by suaveolent** [comment]
Thanks for letting me know. Will update the Readme.
