### ISSUE TITLE
No new Data in the morning from HMS 800W-2T (Bug?) 

### ISSUE THREAD

**Issue by Steffen06** [suaveolent/ha-hoymiles-wifi#80]
**Describe the bug**
No Data after retrieving first Dataset in the morning in Home Assistant until i directly connect to the DTU / Inverter (HMS 800W-2T) with the S-Miles installer App Toolkit.

**Installation, Setting**
1. setup of WIFI (static IPv4 Assigned thru DHCP based on MAC-Adresse)
2. Added DTU / Inverter to Cloud Account for Updates
3. Updated DTU thru Cloudportal to Version V00.01.13_20240604
4. Updated Inverter thru Support to Version V01.02.01 (no other Way possibile)
5. Added DTU / Inverter to Home Assistant via this Integration
6. Used Version of this Integration v0.3.2 (Installed thru HACS)
7. Home Assistant 2024.11.2 (running on an Raspberry Pi 5 4GB; 256 GB SSD)
8. Integration update interval 5s (I don't need (want) Data in the Cloud)

**Behavior**
Since I Installed the DTU/Inverter (about a Week ago) and added it to Home Assistant. I see every morning that the DTU connected and responded to the first request of the Integration. (\~08:11 in the Screenshot 1 below) But after the first Dataset there are no new (changed) Datapoints. If I see that in Home Assistant and than connect to the DTU WIFI and open the Toolkit (and see the Production there) Home Assistant magically starts to receive new Data. (\~8:36 in the Screenshot 1) After that the Integration works with the update interval 5s for the rest of the day. (And collected with the [hoymiles-wifi](https://github.com/suaveolent/hoymiles-wifi) and a small shell Skript all data from get / info functions at [20241119_082854.txt](https://github.com/user-attachments/files/17818265/20241119_082854.txt), [20241119_082854.txt](https://github.com/user-attachments/files/17818265/20241119_082854.txt), [20241119_083014.txt](https://github.com/user-attachments/files/17818266/20241119_083014.txt), [20241119_083529.txt](https://github.com/user-attachments/files/17818267/20241119_083529.txt), [20241119_084040.txt](https://github.com/user-attachments/files/17818268/20241119_084040.txt) & [20241119_093337.txt](https://github.com/user-attachments/files/17818269/20241119_093337.txt)

Screenshot 1:
![Screenshot_20241119_091415_Home Assistant](https://github.com/user-attachments/assets/f6ffe53d-c552-4bab-ae10-4e30edfd05a9)

**second occurrence, whiteout logs / requests**

A few days early I mad an interesting discovery where you can see that the inverter production ramps up (downward trend of the red line in the grape) but the reportet production (Purple line) doesn't get updatet. (Screenshot 2) Here it also helped to open the Toolkit like describe above. But on the first try I only got an error message that the connection failed. (Screenshot 4). On the second connection try the connection worked, but i noticed that the history graph in the App showed the same behavior. (Screenshot 3)

On other occurrences the App sometime looks like it has no history.

Screenshot 2:
![Screenshot_20241116_095800_Home Assistant](https://github.com/user-attachments/assets/a3340206-e8d7-47f6-b748-c9985b3889c9)

Screenshot 3:
![Screenshot_20241116_095338_S-Miles Installer](https://github.com/user-attachments/assets/1f5cbf7e-3c7f-48e5-825d-0eabb74c1068)

Screenshot 4:
![Screenshot_20241116_152524_S-Miles Installer](https://github.com/user-attachments/assets/974fa404-e07a-4e10-a2d9-d248a00f77ce)

**thoughts**
for me It seems that one of the requests / the amount causes something with the DTU that the DTU doesn't report new values and when i try to connect with the S-Miles installer App Toolkit the DTU notices the error and "starts" to send new values. Because in the logs the DTU responds to the requests, but not with new values.

I hope you understand my Problem and you have everything to analyse the problem.

**Comment by suaveolent** [comment]
Thanks for reporting. That is a weird problem you are facing.

To debug it, can you maybe try to increase the update inverval to 35 seconds and see if that solves the issue?

If so, we can then dig deeper and explore what is going on, and what data the toolkit sends to resolve the issue.

**Comment by Steffen06** [comment]
Update with 2 things.
1. with the 35s update interval it worked (Screenshot 1)
2. after testing with 35s update interval i wanted to switch to a 5s interval for the day and then it stoppend working after the change. (Screenshot 2)

- until 08:48:21 running with 35s
- 08:48:21 tried to switch to 5s interval (stoppt retriving new data)
- 08:51:50 switched to 10s interval (did noting)
- 08:54:23 switched back to 35s interval (no new Data)
- connected old Phone to DTU hotspot without opening the S-Miles installer App (unsure if this triggert something; possibly next point was before this timing wise)
- 08:56:08 new Data from DTU (on 3 interval)
- disconnected old Phone from DTU Hotspot (WIFI off)
- 08:59:43 switched to 10s interval (worked without any problem)
- 09:02:16 switched to 5s interval (worked without any problem)

Screenshot 1:
![Screenshot_20241121_Home Assistant](https://github.com/user-attachments/assets/39cb1061-aae8-4dd6-9587-eb9162fa5ebd)

Screenshot 2:
![Screenshot_20241121_Home Assistant_2](https://github.com/user-attachments/assets/8cc6e72f-228b-4887-b928-e81aab35a17f)

**Comment by suaveolent** [comment]
So it seems that connecting to the integrated hotspot triggers some kind of "power mode" which allows to query more than 5 seconds.

Similar to what was observed in https://github.com/suaveolent/hoymiles-wifi/issues/30, 5 seconds only work after connecting via the mobile app (which means that the App is not really responsible for that).

**Comment by Steffen06** [comment]
Ok I try tomorrow again with 35s interval and than changing the interval below 30s (5s steps) without and than back to 35s without connecting to the DTU AP. If i Find out that solution is that you need connect at least once a Day to the DTUs AP than i try setting the Pi on with runs HA to auto connect to the DTU AP. (WIFI of the Pi is currently not used and in close range to the DTU)

**Comment by suaveolent** [comment]
Sounds like a good plan. Let me know if that works for you, so I can update the documentation for this workaround.

**Comment by Steffen06** [comment]
today was a total mess, noting worked as thought :(

- until 09:30:00 35s interval
- 09:30:00 switched to 30s interval (stopped retrieving new data)
- 09:33:04 switched to 20s interval (did nothing)
- \~ 09:35 connected old Phone to DTU AP (did nothing)
- \~ 09:37 disconnected old Phone to DTU AP (did nothing)
- 09:37:30 switched to 35s interval
- 09:38:40 new Data (2 interval)
- 09:40:00 switched to 30s interval (stopped retrieving new data again)
- \~ 09:42 connected old Phone to DTU AP (did nothing)
- 09:43:31 switched to 25s interval (did nothing)
- 09:45:59 switched to 35s interval
- 09:47:09 new Data (2 interval)
- 09:48:30 switched to 5s interval (stopped retrieving new data again, old Phone still connected)
- 09:50:50 initiated restart of DTU through HA
- 09:53:54 DTU disconnected from WIFI ? restart?
- DTU doesn't want to reconnect / stay connected (not sure what happened & why; multiple times entered WIFI credential to initiated reconnection of DTU to WIFI through S-Miles installer App)
- 10:07:44 DTU reconnected (and directly received new Data with 5s interval)

![Screenshot_20241122_Home Assistant](https://github.com/user-attachments/assets/f6a5f0ec-d026-41b3-aeb8-093f3edf2b28)

**Comment by Steffen06** [comment]
Today was better than yesterday.

- 07:41:57 first Dataset with 5s interval (after that no new Data
- \~08:09 connected old phone to DTU AP
- \~08:15 disconnected old phone from DTU AP
- 08:16:07 changed to 35s interval
- 08:17:17 new Data from DTU (on 2 interval)
- 08:20:15 changed to 5s interval (continues working)

It is so confusing what actions enables an interval of 30s or below and then they don't work the next time.

![Screenshot_20241123_Home Assistant](https://github.com/user-attachments/assets/3e10f88e-e309-464a-a007-ad6014e662df)

**Comment by Steffen06** [comment]
Today was again a bit different as yesterday.

- until 09:20:02 with 5s interval (as usual no new Data )
- 09:20:02 changed to 35s interval (works directly)
- 09:24:35 changed to 5s interval (stopped working)
- 09:28:28 changed to 35s interval
- 09:29:38 new Data from DTU (on 2 interval)
- 09:31:31 changed to 5s interval (stopped working)
- \~09:33 connected old phone to DTU AP
- \~09:34 opening S-Miles installer App Toolkit on the old phone
- 09:34:11 new Data from DTU

![Screenshot_20241124_Home Assistant](https://github.com/user-attachments/assets/e93fc81f-4b7c-4ac3-a6c6-5d9eaefbe32d)

**Comment by Steffen06** [comment]
Today was similar to yesterday with the difference that the the Pi on witch runs HA was set up to auto connect to the DTU AP.

- until 08:45:58 with 5s interval (as usual no new Data )
- 08:45:58 changed to 35s interval (works directly)
- 08:46:33 new Data from DTU (on 1 interval)
- 08:48:49 changed to 5s interval (stopped working)
- \~08:49 connected old phone to DTU AP
- \~08:50 opening S-Miles installer App Toolkit on the old phone
- 08:50:24 new Data from DTU

![Screenshot_20241125_Home Assistant](https://github.com/user-attachments/assets/84125ab0-7807-41ee-bab0-5a0d6f18bed2)

**Comment by suaveolent** [comment]
That is weird indeed. I will dig into the App code to see if the mobile app transmits anything before accessing the `get-real-data-new` command.

**Comment by Steffen06** [comment]
In the last few days I also started digging in to what the App sends to the DTU because it shown the same behavior as shown above.

1. The APP toolkit only looks if the current connected WIFI has a certain pattern (I think it's something like DTU.*). If that applies it tries to connect to the DTU otherwise it shows a Message you need to switch the WIFI.
2. The Toolkit always sends the requests to 10.10.100.254(:10081)

So If you want to capture all the traffic you can setup a AP with the Pattern and set a NAT rule with destination nat at the device that creates the AP or in your router. A static route doesn't work.
iptables rule for Linux (HA):
`iptables-nft -t nat -A PREROUTING --destination 10.10.100.254 -j DNAT --to-destination <IP of DTU in Local Network>`

(Up to this Point I have already tested and it works)

I will try tomorrow to capture the first connection from the App Toolkit to the DTU of the Day and try to look in if can find something in comparison to packets send from the Library

**Comment by Steffen06** [comment]
Yesterday I messed up when I tried to capture the Traffic. But Today I was abele to capture everything successfully.

With the help of [Hoymiles-DTU-Proto](https://github.com/henkwiedig/Hoymiles-DTU-Proto) i tried to add direct parsing inside Wireshark with the proto Files but could not get it working and then I found [pcap_parser.py](https://github.com/henkwiedig/Hoymiles-DTU-Proto/blob/main/pcap_parser.py) (slightly modified for my needs) in the repo which can directly decode the pcapng files. (slightly modified for my needs) I hope its helps you.

Red line ==> started to recve Data in Homeassistant.

Traffic between HA and the DTU ([20241201_HA_DTU.txt](https://github.com/user-attachments/files/17970188/20241201_HA_DTU.txt)):
![Screenshot_20241201_HA_DTU](https://github.com/user-attachments/assets/c29c393f-6549-4874-8f1b-77acad7bb7d8)

Traffic between the APP and the DTU from start of the APP until closing the APP ([20241201_APP_DTU.txt](https://github.com/user-attachments/files/17970191/20241201_APP_DTU.txt)):
![Screenshot_20241201_APP_DTU](https://github.com/user-attachments/assets/9a1157c1-b49d-4899-8d1d-2032f371d475)

Data in Homeassistant:
![Screenshot_20241201_Home Assistant](https://github.com/user-attachments/assets/d04809ce-a866-4be5-a229-0a1fa9a2691e)

**Comment by suaveolent** [comment]
Thanks, that really helps a lot! 
So it could be as simple as a heartbeat request? This is already implemented in the library :)

**Comment by Steffen06** [comment]
I don't thin so because  that is something I already covered (see the 20241119_*.txt Files in the initial comment).

Requests the APP makes:
1. HB
2. APPInfoData
3. Command
4. AppGetHistPower

 I think more it is the suspicious Command* with the action: 33, because all other of them are covered described above and tried multipel other times without uploading the results. Or something what isn't covered or the combination of multiple requests potentially timing dependent.

Traffic between HA and the DTU ([20241201_HA_DTU.txt](https://github.com/user-attachments/files/17979314/20241201_HA_DTU.txt)):
![Screenshot_20241202_HA_DTU](https://github.com/user-attachments/assets/11581099-5165-45d7-8b35-237b4a47771d)

Traffic between the APP and the DTU from start of the APP until closing the APP ([20241201_APP_DTU.txt](https://github.com/user-attachments/files/17979327/20241201_APP_DTU.txt)):
![Screenshot_20241202_APP_DTU](https://github.com/user-attachments/assets/d07b1ba8-8f5b-46ad-a084-d8b9a0c07e26)

**Comment by suaveolent** [comment]
Thanks for the clarification. That could indeed be it.

 I just had a look at the source code of the app. Unfortunately, they do not explain what the command `33` does. 
You could try sending that command via the `hoymiles-wifi` lib. If it is successful we could implement that and name it `enable-performance-mode`.

**Comment by Steffen06** [comment]
ok got it implemented yesterday but did a mistake in one line (that's why the test today failed) and ok got it implemented but did a mistake in one line (that's why the test today failed) an corrected and verified with a capture that all values are set correctly  and verified with a capture that all values are set correctly.

**Comment by suaveolent** [comment]
Great, I am really curious if that solves the issue :)

**Comment by Steffen06** [comment]
I am happy to announce that it solves the issue and created a pull request for the library https://github.com/suaveolent/hoymiles-wifi/pull/43

For the HA implementation please add this function also as button besides an automatic implementation so I can trigger it manually if it didn't work automatically.

Traffic between HA and the DTU ([20241204_HA_DTU.txt](https://github.com/user-attachments/files/18006877/20241204_HA_DTU.txt)):
![Screenshot_20241204_HA_DTU](https://github.com/user-attachments/assets/b0558e5a-547f-4958-8c2b-a2b059648416)

**Comment by suaveolent** [comment]
Great find!! Thank you.

I will review the PR as soon as possible and add that button to the integration :)

**Comment by Steffen06** [comment]
Ok At least it looks so for me and worked for me. But I can't guarantee that it always works but I hope so.

**Comment by suaveolent** [comment]
@Steffen06 I have merged the PR today and implemented the button in the `main` branch. Can you update to the `main` branch and check if it works for you?

**Comment by Steffen06** [comment]
It works, but I noticed a new slide for the power-limiting appeared not sure why (I have renamed the old files and copied the new files manually to the custom components folder and then restarted HA)
![Screenshot_20241206_HA_DTU](https://github.com/user-attachments/assets/95d4d96f-c980-4a15-b2ec-9a27ea65884b)
![Screenshot_20241206_Home Assistant](https://github.com/user-attachments/assets/d36ad74b-1295-4a92-bcbf-10d37ed257f2)

**Comment by suaveolent** [comment]
Yes that is expected. I noticed a bug where on multiple inverters it would always generate the same id for the slider. 

This will be documented in the release update. The old sensor can safely be removed.
