### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by thueske** [suaveolent/ha-hoymiles-wifi#86]
Hello,

I have installed a balcony power station with Hoymiles HMS-800-2T. At the moment it is very cloudy and therefore there is little to no production, but I am wondering about the error codes. Where can I find details on this? When I Google it, I can't find anything and there are no errors in the Hoymiles app.

<img width="343" alt="Bildschirmfoto 2024-12-29 um 09 53 59" src="https://github.com/user-attachments/assets/2b1b971e-2b83-4e7a-a316-63e973e8c524" />

**Comment by thueske** [comment]
After a firmware upgrade the errors disappear.

**Comment by suaveolent** [comment]
Great, thanks for letting us know!
